# Generated by Django 2.2.28 on 2022-07-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_useroptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='editor_mode',
            field=models.IntegerField(default=2, verbose_name='编辑器选项'),
        ),
    ]
